application: dovetail-api1
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /p
  static_dir: pages
  
- url: /api.html
  static_files: api.html
  upload: api\.html

- url: /chart/.*
  script: web.main.app

- url: /poll/.*
  script: web.main.app

- url: /.*
  script: api.main.app

libraries:
- name: webapp2
  version: "2.5.1"

- name: ssl
  version: latest

- name: jinja2
  version: latest
  
- name: PIL
  version: latest
  
- name: matplotlib
  version: latest
  
- name: numpy
  version: latest
