application: dovetail-api
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /api.html
  static_files: api.html
  upload: api\.html

- url: /chart/.*
  script: web.main.app

- url: /.*
  script: api.main.app

libraries:
- name: webapp2
  version: "2.5.1"

- name: ssl
  version: latest

- name: jinja2
  version: latest
  
- name: PIL
  version: latest